
CREATE TABLE Drinks (
    id integer generated by default as identity,
    name_eng VARCHAR(255),
    name_ukr VARCHAR(255),
    price DOUBLE PRECISION,
	primary key (id)
);

CREATE TABLE Desserts (
    id integer generated by default as identity,
    name_eng VARCHAR(255),
    name_ukr VARCHAR(255),
    price DOUBLE PRECISION,
	primary key (id)
);

CREATE TABLE Positions (
   id integer generated by default as identity,
   position_name VARCHAR(255),
   primary key (id)
);


CREATE TABLE Staff (
    id integer generated by default as identity,
    full_name VARCHAR(255),
    phone VARCHAR(255),
    email VARCHAR(255),
    position_id INT,
    FOREIGN KEY (position_id) REFERENCES Positions(id),
	primary key (id)
);


CREATE TABLE Customers (
    id integer generated by default as identity,
    full_name VARCHAR(255),
    date_of_birth DATE,
    phone VARCHAR(20),
    email VARCHAR(255),
    discount DECIMAL(5, 2),
	primary key (id)
);

CREATE TABLE Schedule (
    id integer generated by default as identity,
    staff_id INT,
    day_of_week VARCHAR(15),
    start_time TIME,
    end_time TIME,
    FOREIGN KEY (staff_id) REFERENCES Staff(id),
	primary key (id)
);

CREATE TABLE Orders (
    id integer generated by default as identity,
    customer_id INT,
    order_date TIMESTAMP,
    total_amount DECIMAL(10, 2),
    FOREIGN KEY (customer_id) REFERENCES Customers(id),
    primary key (id)
);


CREATE TABLE OrderItems (
    id integer generated by default as identity,
    order_id INT,
    drink_id INT,
    dessert_id INT,
    quantity INT,
    drink_price DECIMAL(5, 2),
    dessert_price DECIMAL(5, 2),
    FOREIGN KEY (order_id) REFERENCES Orders(id),
    FOREIGN KEY (drink_id) REFERENCES Drinks(id),
    FOREIGN KEY (dessert_id) REFERENCES Desserts(id),
	primary key (id)
);

insert into drinks(name_eng,name_ukr,price)values('tea','чай','38'),
('espresso','еспресо','50'),('americano','амерікано','40');

insert into desserts(name_eng,name_ukr,price)values('donut','донат','50'),
('cake','тарталетка','64'),('croissant','круасан','45');

insert into positions(position_name)values('barista'),('waiter'),('confectioner');

insert into staff(full_name,phone,email,position_id)values('Романичев Владимир','+380934567812','romanichev@gmail.com',3),
('Горбунов Игорь','+380671234578','gorbunov@gmail.com',1),
('Лайтарук Сергей','+380957892356','laytaruk@gmail.com',2);

insert into customers(full_name,date_of_birth,phone,email,discount)values('Иванов Иван','01-02-1988','+380671597548','Ivan@gmail.com',5),
('Петров Петр','02-03-2000','+380957531248','Petrov@gmail.com',7),
('Егоров Егор','03-05-1998','+380931234896','Egorov@gmail.com',10);

insert into schedule(staff_id,day_of_week,start_time,end_time)values(1,'Monday','07:00','18:00'),
(2,'Monday','07:00','18:00'),(3,'Monday','07:00','15:00'),(1,'Tuesday','07:00','18:00'),
(2,'Tuesday','07:00','18:00'),(3,'Tuesday','07:00','15:00'),(1,'Wednesday','07:00','18:00'),
(2,'Wednesday','07:00','18:00'),(3,'Wednesday','07:00','15:00'),(1,'Thursday','07:00','18:00'),
(2,'Thursday','07:00','18:00'),(3,'Thursday','07:00','15:00'),(1,'Friday','07:00','18:00'),
(2,'Friday','07:00','18:00'),(3,'Friday','07:00','15:00'),(1,'Saturday','07:00','18:00'),
(2,'Saturday','07:00','18:00'),(3,'Saturday','07:00','15:00'),(1,'Sunday','07:00','18:00'),
(2,'Sunday','07:00','18:00'),(3,'Sunday','07:00','15:00');

insert into Orders(customer_id,order_date,total_amount)values(1,'02-02-2024',83),
(2,'02-02-2024',90),(3,'02-02-2024',114);

insert into OrderItems(order_id,drink_id,dessert_id,quantity,drink_price,dessert_price)values(1,1,3,2,38,45),
(2,3,1,2,40,50),(3,2,2,2,50,64);

